### PR TITLE
Add fix for iOS8 Safari

### PR DESCRIPTION
**Pull request by Lochlan**
This diff addresses the iOS8 Safari issues mentioned in sole/tween.js/issues/145 (specifically [this comment](https://github.com/sole/tween.js/issues/145#issuecomment-62250157))

(I hope the style is sufficiently close to the rest of the code.  As you can see I opted not to add this into the existing ternary, as that seemed like it wouldn't be very readable!)

Compare [my forked gh-pages branch](http://lochlan.github.io/tween.js/examples/01_bars.html) versus [your current gh-pages branch](http://sole.github.io/tween.js/examples/01_bars.html) using Safari on iOS8.

### CODE REVIEW

**Comment by Lochlan** [comment]
Sorry to pester you, but: any chance of getting this merged?  I think iOS8 support is pretty important.

**Comment by asaeed** [comment]
+1 this fix helped me provide ios8 support.  thank you!

**Comment by xiangyongkun** [comment]
thank you!!

**Comment by superlukas** [comment]
This looks a little odd. The first branch should say: If `time !== 'undefined'`, then `time = time`, no? I'm not sure how your PR fixes to problem Safari has. As far as I can tell, the problem is that the values `Date.now` produces just aren't that useful (for tweening, anyway).

Why wouldn't you just polyfill `window.performance.now`, either inside tween.js, or in your own app, passing the time to `TWEEN.update` yourself? [Here's](https://gist.github.com/paulirish/5438650) the polyfill.

**Comment by sole** [comment]
thanks for the PR, @Lochlan  - I'm sorry I didn't see it on time as I missed GH notifications.

We went for #185 - feel free to review if you think something's missing :)

**Pull request closed without merging**
