### PR TITLE
fix(package.json): add export map

### PR DESCRIPTION
**Pull request by christjt**
Running ESM in jest tests (node) isn't working properly with this lib yielding this error:
image

Running [@skypack/package-check](https://www.npmjs.com/package/@skypack/package-check) also validates this.
image

This PR adds export map and after these changes everything is healthy:
image

Package.json `"module"` is legacy and can (and probably should) be removed. You can also concider adding `"type": "module"` to properly indicate that this lib is ESM, but again, I'll leave this to the maintainer to decide.

This may also fix: https://github.com/tweenjs/tween.js/issues/649

### CODE REVIEW

**Comment by trusktr** [comment]
This is great! I do agree we should change to type:module and remove the old field.

We would probably have to release this as a major bump, along with a release note too I think.

Would love to get rid of CJS, and just have ESM.

**Comment by christjt** [comment]
> This is great! I do agree we should change to type:module and remove the old field.
> 
> We would probably have to release this as a major bump, along with a release note too I think.
> 
> Would love to get rid of CJS, and just have ESM.

That all sounds great, but we we can add the exports field without it being a breaking change, right? And then in the future considering to remove the commonjs output if you want.

**Comment by christjt** [comment]
@trusktr

**Comment by trusktr** [comment]
@christjt Hello! I'm in favor of this change for now. I think I would prefer to just ship vanilla ES Modules (no bundle) and let people bundle any way they want (or just import vanilla). Simplifies the setup.

For some reason the build is not running. Do the regular tests pass for you? Can you also add the skypack check to the tests?

**Comment by trusktr** [comment]
Ok, got the darn build fixed. Looks like it was a bug inside GitHub.

**Comment by trusktr** [comment]
Ok, tests passing, gonna just merge and release a major bump!

**Review by trusktr — APPROVED** [review]

**Pull request merged**
