### PR TITLE
Fix CJS entry point

### LINKED ISSUE #649: CJS entry point can't be loaded in Node.js
I might be doing something wrong, but I believe there is an issue with the current dual package setup. Type is set to `module` but the CJS entry point `main` points to "dist/tween.cjs.js". Despite the `.cjs` in there the Node.js loader still sees the final `.js` extension. Based on the nearest `package.json` it will therefore default to using the ESM loader for this file.

As a result, you can't currently `require('@tweenjs/tween.js')` in Node. Unless I'm missing something [the `.js` extension should be dropped](https://github.com/tweenjs/tween.js/blob/main/rollup.config.js#L22).

### PR DESCRIPTION
**Pull request by inukshuk**
Closes #649

### CODE REVIEW

**Comment by pailhead** [comment]
I am unable to import TWEEN with typescript, whatsoever.

**Comment by SilkePilon** [comment]
this needs to be merged rn.....

**Comment by trusktr** [comment]
Hello! Is this still needed after the recent changes in `main`?

The `exports` field now includes the link to the `types`, however the cjs file name has not changed.

Can you import in TypeScript now @pailhead?

Do we still need to change the name @inukshuk?

**Comment by trusktr** [comment]
Yep, the naming needed to be changed. I added an example Node.js CommonJS project in `examples/example-projects/nodejs-commonjs/` to test it out.

Thanks! Merged!

**Comment by trusktr** [comment]
Release in v22.0.0 (major versio bump because the file name changed, just in case anyone somehow relied on the `.cjs.js` file in any way).

**Pull request merged**
