### PR TITLE
Add performance.now polyfill

### PR DESCRIPTION
**Pull request by superlukas**
This should solve the problems people have with tween.js on iOS, as well as improve animation quality in older browsers in general.

### CODE REVIEW

**Comment by superlukas** [comment]
I can fix the failing tests, if you like. I'm not sure tween.js supports non-browser contexts officially anyway.

**Comment by JosephClay** [comment]
+1 Much faster/cleaner than a check on every update

**Comment by dalisoft** [comment]
Before submit please see your code in Chrome Dev-Panel! Your polyfill works normally, but need some  fix!

**Comment by superlukas** [comment]
@dalisoft I did and it worked just fine. Just tell me what's wrong so I can fix it.

**Comment by sole** [comment]
Hi @superlukas - I hadn't seen this PR yet, I'm sorry. Something happened with the notifications.
It looks awesome, I've been meaning to do this for a while so I'm glad you stepped ahead and did that.

I recently moved the project to its own organisation, so I think that might be a reason why Travis isn't too happy. I will look into that. Not sure about errors in Chrome, I haven't tested it...

**Comment by superlukas** [comment]
@sole Yeah I now; don't worry about it :)

The tests fail because `window` isn't available in Node. If you want to support Node as well then just change the naked call to something like  `window ? window.performance.now() : Date.now()`. I didn't choose to not support Node or anything — I just forgot.

I figured there's no point in adding this to the ES5 version anymore given that ES6 is on the agenda now.

**Comment by sole** [comment]
Oh right, I see! That's why they're failing too. Mmm so, I wasn't thinking of canning the es5 version already... there's a lot of people using it and we don't even have an es6 yet :-)

So in order to pass the tests we could either
* add a mini "polyfill" to the tests for them to have a "window" object? although not sure how it'll work with node.js scopes...
* have the tests actually run on a browser e.g. phantom or similar

I think for the sake of running tests locally too, the first option is easier :)

**Comment by superlukas** [comment]
Alright here we go. Don't worry about the mess, I'll squash the commits later. This is not a acceptable solution anyway because of the runtime overhead.

Running the tests in PhantomJS would probably be the best solution although making it work with nodeunit would be way cheaper.

**Comment by superlukas** [comment]
@sole I didn't expect the fix to be that easy. I *think* you can merge the changes now if you like.

**Comment by sole** [comment]
Okay I could finally have a moment to test this one! Looks fine and no errors on Safari / Chrome on Mac. If anyone has a tablet or other iDevice and want to try it out it'd be nice so we can maybe close #145

Merging it in the meantime :) thanks @superlukas !!!

**Pull request merged**
