### PR TITLE
Provided a bower main dependency for an easy integration

### PR DESCRIPTION
**Pull request by azachar**
Hello!
I have created the ``bower.json`` file with specified the main dependency so it can be used in a bower environment without tweeking.

The main dependency is set to ``src/Tween.js`` (if you wish to changed, feel free to do it).

Best regards,
Andrej

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
+1

**Comment by sole** [comment]
Hi @aza

**Comment by azachar** [comment]
Hello @sole!

1. I will change the repo url to tweenjs/tween.js
2. The best is to mention everyone who contributed at least as a courtesy :)

Cheers,
Andrej

**Comment by sole** [comment]
Thanks Andrej!

I'll merge it for now, I will add a "add tween.js authors + contributors link" bug so we point people to the full list of people who've contributed :-)

**Pull request merged**
