### PR TITLE
Add tween to nested object

### PR DESCRIPTION
**Pull request by FlorianBELLAZOUZ**
Hi there !

In reaction to this issues  #52 #78, I sugest this simple API :

With this PR Tween.js can now change properties across nested object, to do this you just need to use a string path pointing to the properties. For example:

```javascript
var nestedObject = { scale: { x:0, y:0 } }

var tween = new TWEEN.Tween(nestedObject).to({ 'scale.x': 100, 'scale.y': 100 });
```

This PR includes UnitTests and Documentation.

I'm open to any sugestion.

### CODE REVIEW

**Comment by FlorianBELLAZOUZ** [comment]
I add the posibility to use array tween with nested object.

```js
var obj = { scale: { x: 0 } };

var t = new TWEEN.Tween( obj ).to( { 'scale.x': [ 50, 100 ] }, 100 );
```

By the way i fix and unitTest the issues #150

```js
var obj = { scale: { x: 100 } };

var t = new TWEEN.Tween( obj ).to( { 'scale.x': [ '+50', '+100' ] }, 100 );
```

**Comment by dalisoft** [comment]
It looks nice. I test it. If works i add this to my library and give you credit author note

**Comment by dalisoft** [comment]
Very nice. It works, but calling on every frame is just performance-killer

**Comment by FlorianBELLAZOUZ** [comment]
Hi @dalisoft thanks,

Can you provide some code and benchmark ?

**Comment by mikebolt** [comment]
Thanks for the PR. I think this is a much-needed feature. It can help with tweening certain Three.js objects. I like the API with dot notation. We might also want to support using a nested object as the target without the dot notation, for example:

    var t = new TWEEN.Tween({rotation: 5, position: {x: 4, y: 8}}).to({rotation: 12, position: {x:5, y:5}}, 4000);

I am worried about performance in the standard use-case, where tweens are not grouped. I think we will need to perform some tests to make sure. If there is a performance hit, then I have a few ideas for making it more efficient.

I am not worried about performance when using nested tweens. If it's a bit slower, that's OK. But we don't want to make existing code slower.

**Comment by trusktr** [comment]
@FlorianBELLAZOUZ Thanks for bringing up the good idea for nested tweening, however closing in favor of https://github.com/tweenjs/tween.js/pull/366.

**Pull request closed without merging**
