### PR TITLE
Migration to Typescript maintaining backward compatibility.

### PR DESCRIPTION
**Pull request by nidorx**
Migration to Typescript **maintaining backward compatibility**.

1. Pass all original tests and examples without change
2. **eslint** - Uses the recommended rules from the `@typescript-eslint/eslint-plugin` (`@typescript-eslint/recommended`, `prettier/@typescript-eslint`, `prettier/recommended` )
3. Resolved dependency vulnerabilities:

**before**
```
$ npm i
audited 1045 packages in 3.265s
found 79 vulnerabilities (23 low, 20 moderate, 35 high, 1 critical)
```
**now**
```
$ npm i
audited 897 packages in 2.437s
found 0 vulnerabilities
```

### CODE REVIEW

**Comment by mikebolt** [comment]
Hi, I missed this until now. I will take a look soon.

**Comment by qelix** [comment]
Any news on when this will be reviewed/merged?

**Comment by AlanRynne** [comment]
I would also love to see this one merged 😄 Not having typescript definitions is driving me crazy!

**Comment by miltoncandelero** [comment]
> I would also love to see this one merged 😄 Not having typescript definitions is driving me crazy!

There are typescript definitions: https://www.npmjs.com/package/@types/tween.js

(don't get me wrong, I'd love to see this merged too)

**Comment by AlanRynne** [comment]
My experience is that the definitions are lacking not complete. I never get autocomplete for `Tween.Easing` for example.

**Comment by nidorx** [comment]
For now I published a package on the npm that I'm using:  ttps://www.npmjs.com/package/tween.ts

To use:
```
npm install --save tween.ts

// ...
import TWEEN from "tween.ts";

new TWEEN.Tween(particle.mesh.scale)
                     .to ({
                         x: Math.random () * 1 + 0.7,
                         y: Math.random () * 1 + 0.7,
                         z: Math.random () * 1 + 0.7,
                     })
                     .delay (0.1)
                     .duration (Math.random () * 1 + 0.3)
                     .easing (TWEEN.Easing.Quartic.Out);
```

**Comment by AlanRynne** [comment]
Will check it out this weekend! I might actually make the switch for a project I’m shuts started. Thanks!

**Comment by trusktr** [comment]
Sorry for the delays! I would like to get things rolling. Tracking this in the new pull request tracking board: https://github.com/tweenjs/tween.js/projects/4

I'd like to move to GitHub Actions to get automated tests running again, so we can more easily test pull request changes (though this PR already has a recorded passing state).

**Comment by trusktr** [comment]
Need to figure out how to best handle this. It will conflict with other PRs. It would be easier to have one PR that keep just the single `Tween.js` file, but converts to ES2015 classes. Then a second PR would convert that to `Tween.ts` and the change would be tracked as mostly a rename. Then a third PR could further organize code into separate files (which is apart from the code being TS or JS).

It'll be easier that way to merge the other changes.

**Comment by trusktr** [comment]
I am in process of merging fixes. It will surely cause merge conflicts. It'll be easier to manage that if the structure of the code remains the same.

**Comment by trusktr** [comment]
I've merged several old PRs / bug fixes. I'm aiming to get this merged this weekend.

**Comment by trusktr** [comment]
I made a bunch of merges and some fixes this weekend, but I think I'm out of time for this weekend.

If no one gets to it before I do next weekend, my plan is

- to branch from this,-
- revert the changes
- cherry-pick the TypeScript configuration in a commit after the revert,
- then effectively do the same transformation of the source but without structural changes (saving that for later). 

In the end, the original commits of this PR will still be there so you can get credit for it @nidorx.

**Comment by trusktr** [comment]
Moved to https://github.com/tweenjs/tween.js/pull/544 so I can make some further changes there before merging.

**Pull request closed without merging**
