### PR TITLE
fix: endless concat

### LINKED ISSUE #620: tweening to arrays of values has bug
`_valuesEnd[property]`'s length will grow endless, because it's a reference to `this.valuesEnd`

https://github.com/tweenjs/tween.js/blob/8db070d25a82c19772352bbcbc33a326e6882b4e/src/Tween.ts#L138-L150

checking this demo, just click the start button twice or more: https://jsbin.com/hulidowipa/edit?html,js,output

### PR DESCRIPTION
**Pull request by tvytlx**
This pr fix #620

### CODE REVIEW

**Comment by trusktr** [comment]
@tvytlx Hello! I would love to get this in. It needs a unit test update 🙏.

**Comment by tvytlx** [comment]
@trusktr request review

**Comment by trusktr** [comment]
@tvytlx thanks for adding the test! Sorry for the late approval.

Btw, are you interested in helping with the project? We're looking for more people to help maintain and expand Tween.js: https://github.com/tweenjs/tween.js/issues/638

**Comment by trusktr** [comment]
Oops, this went into the `master` branch, but we are now using `main` instead of `master`. I will fix it. Thanks for the contribution!

**Pull request merged**
