### PR TITLE
Tween.group

### PR DESCRIPTION
**Pull request by dalisoft**
@sole, @mikebolt, @webmarkelov, @usefulthink please review this my commit

## Why
* for Fix to: #260, #299.

### NOTE:
* if this will be merged, i would be happy to add new features.
* demo already added

### Examples (and methods comment)
```javascript
let groupTween = new TWEEN.Group({
groupVars1:{x:0},
groupVars2:{y:0}
});

// #to
// tweens {x:0} => {x:50} in 2s and {y:0} => {y:50} in 1s
   groupTween.to({
groupVars1:{x:50},
groupVars2:{y:50}
}, {
groupVars1: 2000,
groupVars2: 1000
}); // same as TWEEN.Tween.to

let tweenObj = {j:0};
let tween1 = new TWEEN.Tween(tweenObj).to({j: 100}, 1000);

// #insert
groupTween.insert(tween1); // adds to grouping and tweens together with TWEEN.Group tweens

// #easing, #interpolation, #delay, #repeat => #METHOD_STATIC
groupTween[METHOD_STATIC]({
groupVars1: TWEEN.Easing.Elastic.InOut,
groupVars2: TWEEN.Easing.Bounce.Out
})

//#start
groupTween.start(time) // time: all defined in-group tweens, does same as TWEEN.Tween#start(time) but for all tweens

//#stop
groupTween.stop() // stop all tweens defined in group

//#filter
groupTweens.filter(tween => tween.isPlaying()); // removes paused/stopped tweens from in-group tweens list

//#erase
groupTween.erase(tween1) // finds tween1 from group tweens then removes from it

//#onUpdate
groupTween.onUpdate(function(object, elapsed){
// object => total all mixed properties tween object
// elapsed => total elapsed number ( 0 ... 1 ) with calculating all tweens elapsed it gives overall elapsed of group tween
})
```

### CODE REVIEW

**Comment by usefulthink** [comment]
First of all, I am not a maintainer of the project, so this is kind of an outside view. It is also not an exhaustive review: I didn't really look into the use-cases covered by your implementation and the API-surface it provides. This is more about the coding-style and overall structure.

In general, you should really try to adjust yourself to the coding-style used in the project. Two points to make here:

 - tween.js has it's UMD-Wrapper at the bottom and uses a completely different structure for the source-file (for instance how re-initialization is prevented). While this might be a matter of taste (there is no one solution that is subjectively "better" than another) it is the taste and preference of the creators and maintainers that counts. You might disagree, but it's their project so there's that.

 - you are writing in your commit-summary that you are not interested in node. However this project is written to be compatible with node, so you really can't just ignore that.

Then some things about the code:

 - there are several helper-functions defined (`var _helper = {...}`), some of which aren't even used and the others being used just a single time. I think it might be better and easier to read to inline these functions. 
 - basically the same goes for the `_ev.emit`-function. It is only used to be assigned to `TWEEN.Event.Emitter` (btw. if you're using the naming from node it'd be better to also adapt the semantics, otherwise people will be confused) but that in turn is never used. Not sure why you added it, but it apparently has nothing to do with the `TWEEN.Group`-implementation.
 - I would recommend against using abbreviated names for variables (use `object` instead of `obj`, `value` instead of `val`). It generally improves readability and removes ambiguity.
 - some variable- and method-names should be improved. For instance, the function-name `listenTweens` suggests it has something to do with events, where all it does is `_listOfTweens.forEach()` (as said before, helper-functions like this one should probably better be inlined). Think about what someone might think the variables contain without having read all the code. Another example: You are using names like `getDuration` or `getValue` for simple values. Those names suggest to me they are functions (I think I have to call `getValue()` to get the actual value).
 - you are mixing variables with underscore-prefix and without with no apparent reason.
 - generally, I find the code a bit confusing and after reading it for like 20 minutes i still have no clear idea what it does, why it does that and how its done (this wasn't the case for tween.js itself).

**Comment by dalisoft** [comment]
Like before my PRs this is too not reviewed nor merged. So i close this. Get, change, adapt and improve myself is better, faster and effecient than wait a PR

**Comment by mikebolt** [comment]
I don't see anything in this PR that will break node.js. We might have to change a few things to support having separate source files, but that's not an issue.

We will need to add some tests and some documentation. I can help with that. Could you briefly explain what each method does?

I think the most important feature is the ability to control tween groups separately. That was the original issue I had with tween.js that brought me to look at the source code and start helping out with this project. I would like to see an example where you can control two different "groups" of tweens separately, for example with a start and a stop button for each group. Instead of using TWEEN.update, we will have to use an "update" method of the tween group. I think a simple for-each will work, where inside the loop you use each tween's update method.

**Comment by dalisoft** [comment]
@mikebolt see updated comment (first commend), which includes small comment about what it does, but about tests i still learning.

**Comment by mikebolt** [comment]
Tween groups are now in master.

**Comment by flavia-it** [comment]
@mikebolt This Ticket has nothing to do with #346. @dalisoft and @alexburner just used the same name for their ideas...

**Comment by alexburner** [comment]
Oo yeah I had been wondering about that: https://github.com/tweenjs/tween.js/pull/346#issuecomment-311551071

**Pull request closed without merging**
