### PR TITLE
Fix lookup of global variables (was broken with Webpack + Babel)

### LINKED ISSUE #292: Tween.js:75 Uncaught TypeError: Cannot read property 'window' of undefined
image

Can't figure out why I'm getting this. I just include Tween.js raw in my bundle. Maybe a guard could bedded checking that `this` is not undefined?

I'm on Chrome Version 53.0.2785.116 (64-bit)

### PR DESCRIPTION
**Pull request by haggholm**
Fixes #292 for me.

### CODE REVIEW

**Comment by webmarkelov** [comment]
It works with webpack,  for example: ```javascript import TWEEN from 'tween.js' ```

**Comment by haggholm** [comment]
For me, it threw errors because the `this` that’s being bound is `undefined`. I presume(d) it had to do with Webpack; I don’t really know that for a fact. What I do know is that my build (which uses Webpack and Babel) now works…

**Comment by mikebolt** [comment]
According to the EcmaScript 5 spec, 'this' is bound to the global object:
https://www.ecma-international.org/ecma-262/5.1/#sec-10.4.1.1

Also in the EcmaScript 6 spec:
http://www.ecma-international.org/ecma-262/6.0/#sec-lexical-environments

That means that there's a problem somewhere else.

I wrote the code as it is because I was getting the "ReferenceError: window
is not defined" error in node.js. I was not aware that the "typeof"
operator magically protected against this error. I will test this out over
the weekend, maybe.

**Comment by mikebolt** [comment]
OK, it works with my version of node (v 4.4.4). I also removed the function that wrapped the performance.now polyfill because it is no longer necessary.

**Pull request merged**
