### PR TITLE
bug-fix: update function still be called after end();

### PR DESCRIPTION
**Pull request by Nafeng**

### CODE REVIEW

**Comment by mikebolt** [comment]
Hi. Thanks for the help!

I will review this soon. I need to reproduce the issue then make sure that this fixes it.

**Comment by Nafeng** [comment]
> Hi. Thanks for the help!
> 
> I will review this soon. I need to reproduce the issue then make sure that this fixes it.

Did this fix it?

**Comment by trusktr** [comment]
Sorry for the delays @Nafeng! I would like to get things rolling. Tracking this in the new pull request tracking board: https://github.com/tweenjs/tween.js/projects/4

I'd like to move to GitHub Actions to get automated tests running again, so we can more easily test pull request changes.

**Comment by trusktr** [comment]
@Nafeng Moving this to https://github.com/tweenjs/tween.js/pull/529 to I can make some changes.

**Pull request closed without merging**
